// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/protobuf/kademlia.proto

package org.ogreg.sdis.kademlia;

public final class Protocol {
  private Protocol() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public enum MessageType
      implements com.google.protobuf.ProtocolMessageEnum {
    REQ_PING(0, 0),
    REQ_STORE(1, 1),
    REQ_FIND_NODE(2, 2),
    REQ_FIND_VALUE(3, 3),
    RSP_SUCCESS(4, 10),
    RSP_IO_ERROR(5, 11),
    ;
    
    public static final int REQ_PING_VALUE = 0;
    public static final int REQ_STORE_VALUE = 1;
    public static final int REQ_FIND_NODE_VALUE = 2;
    public static final int REQ_FIND_VALUE_VALUE = 3;
    public static final int RSP_SUCCESS_VALUE = 10;
    public static final int RSP_IO_ERROR_VALUE = 11;
    
    
    public final int getNumber() { return value; }
    
    public static MessageType valueOf(int value) {
      switch (value) {
        case 0: return REQ_PING;
        case 1: return REQ_STORE;
        case 2: return REQ_FIND_NODE;
        case 3: return REQ_FIND_VALUE;
        case 10: return RSP_SUCCESS;
        case 11: return RSP_IO_ERROR;
        default: return null;
      }
    }
    
    public static com.google.protobuf.Internal.EnumLiteMap<MessageType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<MessageType>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<MessageType>() {
            public MessageType findValueByNumber(int number) {
              return MessageType.valueOf(number);
            }
          };
    
    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return org.ogreg.sdis.kademlia.Protocol.getDescriptor().getEnumTypes().get(0);
    }
    
    private static final MessageType[] VALUES = {
      REQ_PING, REQ_STORE, REQ_FIND_NODE, REQ_FIND_VALUE, RSP_SUCCESS, RSP_IO_ERROR, 
    };
    
    public static MessageType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }
    
    private final int index;
    private final int value;
    
    private MessageType(int index, int value) {
      this.index = index;
      this.value = value;
    }
    
    // @@protoc_insertion_point(enum_scope:org.ogreg.sdis.kademlia.MessageType)
  }
  
  public interface NodeOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required bytes nodeId = 1;
    boolean hasNodeId();
    com.google.protobuf.ByteString getNodeId();
    
    // required bytes address = 2;
    boolean hasAddress();
    com.google.protobuf.ByteString getAddress();
    
    // required uint32 port = 3;
    boolean hasPort();
    int getPort();
  }
  public static final class Node extends
      com.google.protobuf.GeneratedMessage
      implements NodeOrBuilder {
    // Use Node.newBuilder() to construct.
    private Node(Builder builder) {
      super(builder);
    }
    private Node(boolean noInit) {}
    
    private static final Node defaultInstance;
    public static Node getDefaultInstance() {
      return defaultInstance;
    }
    
    public Node getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.ogreg.sdis.kademlia.Protocol.internal_static_org_ogreg_sdis_kademlia_Node_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.ogreg.sdis.kademlia.Protocol.internal_static_org_ogreg_sdis_kademlia_Node_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required bytes nodeId = 1;
    public static final int NODEID_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString nodeId_;
    public boolean hasNodeId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public com.google.protobuf.ByteString getNodeId() {
      return nodeId_;
    }
    
    // required bytes address = 2;
    public static final int ADDRESS_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString address_;
    public boolean hasAddress() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public com.google.protobuf.ByteString getAddress() {
      return address_;
    }
    
    // required uint32 port = 3;
    public static final int PORT_FIELD_NUMBER = 3;
    private int port_;
    public boolean hasPort() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public int getPort() {
      return port_;
    }
    
    private void initFields() {
      nodeId_ = com.google.protobuf.ByteString.EMPTY;
      address_ = com.google.protobuf.ByteString.EMPTY;
      port_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasNodeId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasAddress()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPort()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, nodeId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, address_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeUInt32(3, port_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, nodeId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, address_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(3, port_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static org.ogreg.sdis.kademlia.Protocol.Node parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.ogreg.sdis.kademlia.Protocol.Node parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.ogreg.sdis.kademlia.Protocol.Node parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.ogreg.sdis.kademlia.Protocol.Node parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.ogreg.sdis.kademlia.Protocol.Node parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.ogreg.sdis.kademlia.Protocol.Node parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.ogreg.sdis.kademlia.Protocol.Node parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.ogreg.sdis.kademlia.Protocol.Node parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.ogreg.sdis.kademlia.Protocol.Node parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.ogreg.sdis.kademlia.Protocol.Node parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.ogreg.sdis.kademlia.Protocol.Node prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.ogreg.sdis.kademlia.Protocol.NodeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.ogreg.sdis.kademlia.Protocol.internal_static_org_ogreg_sdis_kademlia_Node_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.ogreg.sdis.kademlia.Protocol.internal_static_org_ogreg_sdis_kademlia_Node_fieldAccessorTable;
      }
      
      // Construct using org.ogreg.sdis.kademlia.Protocol.Node.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        nodeId_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        address_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        port_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.ogreg.sdis.kademlia.Protocol.Node.getDescriptor();
      }
      
      public org.ogreg.sdis.kademlia.Protocol.Node getDefaultInstanceForType() {
        return org.ogreg.sdis.kademlia.Protocol.Node.getDefaultInstance();
      }
      
      public org.ogreg.sdis.kademlia.Protocol.Node build() {
        org.ogreg.sdis.kademlia.Protocol.Node result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private org.ogreg.sdis.kademlia.Protocol.Node buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        org.ogreg.sdis.kademlia.Protocol.Node result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public org.ogreg.sdis.kademlia.Protocol.Node buildPartial() {
        org.ogreg.sdis.kademlia.Protocol.Node result = new org.ogreg.sdis.kademlia.Protocol.Node(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.nodeId_ = nodeId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.address_ = address_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.port_ = port_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.ogreg.sdis.kademlia.Protocol.Node) {
          return mergeFrom((org.ogreg.sdis.kademlia.Protocol.Node)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(org.ogreg.sdis.kademlia.Protocol.Node other) {
        if (other == org.ogreg.sdis.kademlia.Protocol.Node.getDefaultInstance()) return this;
        if (other.hasNodeId()) {
          setNodeId(other.getNodeId());
        }
        if (other.hasAddress()) {
          setAddress(other.getAddress());
        }
        if (other.hasPort()) {
          setPort(other.getPort());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasNodeId()) {
          
          return false;
        }
        if (!hasAddress()) {
          
          return false;
        }
        if (!hasPort()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              nodeId_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              address_ = input.readBytes();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              port_ = input.readUInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required bytes nodeId = 1;
      private com.google.protobuf.ByteString nodeId_ = com.google.protobuf.ByteString.EMPTY;
      public boolean hasNodeId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public com.google.protobuf.ByteString getNodeId() {
        return nodeId_;
      }
      public Builder setNodeId(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        nodeId_ = value;
        onChanged();
        return this;
      }
      public Builder clearNodeId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        nodeId_ = getDefaultInstance().getNodeId();
        onChanged();
        return this;
      }
      
      // required bytes address = 2;
      private com.google.protobuf.ByteString address_ = com.google.protobuf.ByteString.EMPTY;
      public boolean hasAddress() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public com.google.protobuf.ByteString getAddress() {
        return address_;
      }
      public Builder setAddress(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        address_ = value;
        onChanged();
        return this;
      }
      public Builder clearAddress() {
        bitField0_ = (bitField0_ & ~0x00000002);
        address_ = getDefaultInstance().getAddress();
        onChanged();
        return this;
      }
      
      // required uint32 port = 3;
      private int port_ ;
      public boolean hasPort() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public int getPort() {
        return port_;
      }
      public Builder setPort(int value) {
        bitField0_ |= 0x00000004;
        port_ = value;
        onChanged();
        return this;
      }
      public Builder clearPort() {
        bitField0_ = (bitField0_ & ~0x00000004);
        port_ = 0;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:org.ogreg.sdis.kademlia.Node)
    }
    
    static {
      defaultInstance = new Node(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:org.ogreg.sdis.kademlia.Node)
  }
  
  public interface MessageOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required bytes nodeId = 1;
    boolean hasNodeId();
    com.google.protobuf.ByteString getNodeId();
    
    // required bytes rpcId = 2;
    boolean hasRpcId();
    com.google.protobuf.ByteString getRpcId();
    
    // required .org.ogreg.sdis.kademlia.MessageType type = 3;
    boolean hasType();
    org.ogreg.sdis.kademlia.Protocol.MessageType getType();
    
    // optional bytes key = 4;
    boolean hasKey();
    com.google.protobuf.ByteString getKey();
    
    // optional bytes data = 5;
    boolean hasData();
    com.google.protobuf.ByteString getData();
    
    // repeated .org.ogreg.sdis.kademlia.Node nodes = 6;
    java.util.List<org.ogreg.sdis.kademlia.Protocol.Node> 
        getNodesList();
    org.ogreg.sdis.kademlia.Protocol.Node getNodes(int index);
    int getNodesCount();
    java.util.List<? extends org.ogreg.sdis.kademlia.Protocol.NodeOrBuilder> 
        getNodesOrBuilderList();
    org.ogreg.sdis.kademlia.Protocol.NodeOrBuilder getNodesOrBuilder(
        int index);
  }
  public static final class Message extends
      com.google.protobuf.GeneratedMessage
      implements MessageOrBuilder {
    // Use Message.newBuilder() to construct.
    private Message(Builder builder) {
      super(builder);
    }
    private Message(boolean noInit) {}
    
    private static final Message defaultInstance;
    public static Message getDefaultInstance() {
      return defaultInstance;
    }
    
    public Message getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.ogreg.sdis.kademlia.Protocol.internal_static_org_ogreg_sdis_kademlia_Message_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.ogreg.sdis.kademlia.Protocol.internal_static_org_ogreg_sdis_kademlia_Message_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required bytes nodeId = 1;
    public static final int NODEID_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString nodeId_;
    public boolean hasNodeId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public com.google.protobuf.ByteString getNodeId() {
      return nodeId_;
    }
    
    // required bytes rpcId = 2;
    public static final int RPCID_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString rpcId_;
    public boolean hasRpcId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public com.google.protobuf.ByteString getRpcId() {
      return rpcId_;
    }
    
    // required .org.ogreg.sdis.kademlia.MessageType type = 3;
    public static final int TYPE_FIELD_NUMBER = 3;
    private org.ogreg.sdis.kademlia.Protocol.MessageType type_;
    public boolean hasType() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public org.ogreg.sdis.kademlia.Protocol.MessageType getType() {
      return type_;
    }
    
    // optional bytes key = 4;
    public static final int KEY_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString key_;
    public boolean hasKey() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public com.google.protobuf.ByteString getKey() {
      return key_;
    }
    
    // optional bytes data = 5;
    public static final int DATA_FIELD_NUMBER = 5;
    private com.google.protobuf.ByteString data_;
    public boolean hasData() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public com.google.protobuf.ByteString getData() {
      return data_;
    }
    
    // repeated .org.ogreg.sdis.kademlia.Node nodes = 6;
    public static final int NODES_FIELD_NUMBER = 6;
    private java.util.List<org.ogreg.sdis.kademlia.Protocol.Node> nodes_;
    public java.util.List<org.ogreg.sdis.kademlia.Protocol.Node> getNodesList() {
      return nodes_;
    }
    public java.util.List<? extends org.ogreg.sdis.kademlia.Protocol.NodeOrBuilder> 
        getNodesOrBuilderList() {
      return nodes_;
    }
    public int getNodesCount() {
      return nodes_.size();
    }
    public org.ogreg.sdis.kademlia.Protocol.Node getNodes(int index) {
      return nodes_.get(index);
    }
    public org.ogreg.sdis.kademlia.Protocol.NodeOrBuilder getNodesOrBuilder(
        int index) {
      return nodes_.get(index);
    }
    
    private void initFields() {
      nodeId_ = com.google.protobuf.ByteString.EMPTY;
      rpcId_ = com.google.protobuf.ByteString.EMPTY;
      type_ = org.ogreg.sdis.kademlia.Protocol.MessageType.REQ_PING;
      key_ = com.google.protobuf.ByteString.EMPTY;
      data_ = com.google.protobuf.ByteString.EMPTY;
      nodes_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasNodeId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasRpcId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getNodesCount(); i++) {
        if (!getNodes(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, nodeId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, rpcId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeEnum(3, type_.getNumber());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, key_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, data_);
      }
      for (int i = 0; i < nodes_.size(); i++) {
        output.writeMessage(6, nodes_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, nodeId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, rpcId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, type_.getNumber());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, key_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, data_);
      }
      for (int i = 0; i < nodes_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, nodes_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static org.ogreg.sdis.kademlia.Protocol.Message parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.ogreg.sdis.kademlia.Protocol.Message parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.ogreg.sdis.kademlia.Protocol.Message parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.ogreg.sdis.kademlia.Protocol.Message parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.ogreg.sdis.kademlia.Protocol.Message parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.ogreg.sdis.kademlia.Protocol.Message parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.ogreg.sdis.kademlia.Protocol.Message parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.ogreg.sdis.kademlia.Protocol.Message parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.ogreg.sdis.kademlia.Protocol.Message parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.ogreg.sdis.kademlia.Protocol.Message parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.ogreg.sdis.kademlia.Protocol.Message prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.ogreg.sdis.kademlia.Protocol.MessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.ogreg.sdis.kademlia.Protocol.internal_static_org_ogreg_sdis_kademlia_Message_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.ogreg.sdis.kademlia.Protocol.internal_static_org_ogreg_sdis_kademlia_Message_fieldAccessorTable;
      }
      
      // Construct using org.ogreg.sdis.kademlia.Protocol.Message.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getNodesFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        nodeId_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        rpcId_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        type_ = org.ogreg.sdis.kademlia.Protocol.MessageType.REQ_PING;
        bitField0_ = (bitField0_ & ~0x00000004);
        key_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        data_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000010);
        if (nodesBuilder_ == null) {
          nodes_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000020);
        } else {
          nodesBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.ogreg.sdis.kademlia.Protocol.Message.getDescriptor();
      }
      
      public org.ogreg.sdis.kademlia.Protocol.Message getDefaultInstanceForType() {
        return org.ogreg.sdis.kademlia.Protocol.Message.getDefaultInstance();
      }
      
      public org.ogreg.sdis.kademlia.Protocol.Message build() {
        org.ogreg.sdis.kademlia.Protocol.Message result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private org.ogreg.sdis.kademlia.Protocol.Message buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        org.ogreg.sdis.kademlia.Protocol.Message result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public org.ogreg.sdis.kademlia.Protocol.Message buildPartial() {
        org.ogreg.sdis.kademlia.Protocol.Message result = new org.ogreg.sdis.kademlia.Protocol.Message(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.nodeId_ = nodeId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.rpcId_ = rpcId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.key_ = key_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.data_ = data_;
        if (nodesBuilder_ == null) {
          if (((bitField0_ & 0x00000020) == 0x00000020)) {
            nodes_ = java.util.Collections.unmodifiableList(nodes_);
            bitField0_ = (bitField0_ & ~0x00000020);
          }
          result.nodes_ = nodes_;
        } else {
          result.nodes_ = nodesBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.ogreg.sdis.kademlia.Protocol.Message) {
          return mergeFrom((org.ogreg.sdis.kademlia.Protocol.Message)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(org.ogreg.sdis.kademlia.Protocol.Message other) {
        if (other == org.ogreg.sdis.kademlia.Protocol.Message.getDefaultInstance()) return this;
        if (other.hasNodeId()) {
          setNodeId(other.getNodeId());
        }
        if (other.hasRpcId()) {
          setRpcId(other.getRpcId());
        }
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasKey()) {
          setKey(other.getKey());
        }
        if (other.hasData()) {
          setData(other.getData());
        }
        if (nodesBuilder_ == null) {
          if (!other.nodes_.isEmpty()) {
            if (nodes_.isEmpty()) {
              nodes_ = other.nodes_;
              bitField0_ = (bitField0_ & ~0x00000020);
            } else {
              ensureNodesIsMutable();
              nodes_.addAll(other.nodes_);
            }
            onChanged();
          }
        } else {
          if (!other.nodes_.isEmpty()) {
            if (nodesBuilder_.isEmpty()) {
              nodesBuilder_.dispose();
              nodesBuilder_ = null;
              nodes_ = other.nodes_;
              bitField0_ = (bitField0_ & ~0x00000020);
              nodesBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getNodesFieldBuilder() : null;
            } else {
              nodesBuilder_.addAllMessages(other.nodes_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasNodeId()) {
          
          return false;
        }
        if (!hasRpcId()) {
          
          return false;
        }
        if (!hasType()) {
          
          return false;
        }
        for (int i = 0; i < getNodesCount(); i++) {
          if (!getNodes(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              nodeId_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              rpcId_ = input.readBytes();
              break;
            }
            case 24: {
              int rawValue = input.readEnum();
              org.ogreg.sdis.kademlia.Protocol.MessageType value = org.ogreg.sdis.kademlia.Protocol.MessageType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(3, rawValue);
              } else {
                bitField0_ |= 0x00000004;
                type_ = value;
              }
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              key_ = input.readBytes();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              data_ = input.readBytes();
              break;
            }
            case 50: {
              org.ogreg.sdis.kademlia.Protocol.Node.Builder subBuilder = org.ogreg.sdis.kademlia.Protocol.Node.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addNodes(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required bytes nodeId = 1;
      private com.google.protobuf.ByteString nodeId_ = com.google.protobuf.ByteString.EMPTY;
      public boolean hasNodeId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public com.google.protobuf.ByteString getNodeId() {
        return nodeId_;
      }
      public Builder setNodeId(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        nodeId_ = value;
        onChanged();
        return this;
      }
      public Builder clearNodeId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        nodeId_ = getDefaultInstance().getNodeId();
        onChanged();
        return this;
      }
      
      // required bytes rpcId = 2;
      private com.google.protobuf.ByteString rpcId_ = com.google.protobuf.ByteString.EMPTY;
      public boolean hasRpcId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public com.google.protobuf.ByteString getRpcId() {
        return rpcId_;
      }
      public Builder setRpcId(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        rpcId_ = value;
        onChanged();
        return this;
      }
      public Builder clearRpcId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        rpcId_ = getDefaultInstance().getRpcId();
        onChanged();
        return this;
      }
      
      // required .org.ogreg.sdis.kademlia.MessageType type = 3;
      private org.ogreg.sdis.kademlia.Protocol.MessageType type_ = org.ogreg.sdis.kademlia.Protocol.MessageType.REQ_PING;
      public boolean hasType() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public org.ogreg.sdis.kademlia.Protocol.MessageType getType() {
        return type_;
      }
      public Builder setType(org.ogreg.sdis.kademlia.Protocol.MessageType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000004;
        type_ = value;
        onChanged();
        return this;
      }
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000004);
        type_ = org.ogreg.sdis.kademlia.Protocol.MessageType.REQ_PING;
        onChanged();
        return this;
      }
      
      // optional bytes key = 4;
      private com.google.protobuf.ByteString key_ = com.google.protobuf.ByteString.EMPTY;
      public boolean hasKey() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public com.google.protobuf.ByteString getKey() {
        return key_;
      }
      public Builder setKey(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        key_ = value;
        onChanged();
        return this;
      }
      public Builder clearKey() {
        bitField0_ = (bitField0_ & ~0x00000008);
        key_ = getDefaultInstance().getKey();
        onChanged();
        return this;
      }
      
      // optional bytes data = 5;
      private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
      public boolean hasData() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public com.google.protobuf.ByteString getData() {
        return data_;
      }
      public Builder setData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        data_ = value;
        onChanged();
        return this;
      }
      public Builder clearData() {
        bitField0_ = (bitField0_ & ~0x00000010);
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }
      
      // repeated .org.ogreg.sdis.kademlia.Node nodes = 6;
      private java.util.List<org.ogreg.sdis.kademlia.Protocol.Node> nodes_ =
        java.util.Collections.emptyList();
      private void ensureNodesIsMutable() {
        if (!((bitField0_ & 0x00000020) == 0x00000020)) {
          nodes_ = new java.util.ArrayList<org.ogreg.sdis.kademlia.Protocol.Node>(nodes_);
          bitField0_ |= 0x00000020;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          org.ogreg.sdis.kademlia.Protocol.Node, org.ogreg.sdis.kademlia.Protocol.Node.Builder, org.ogreg.sdis.kademlia.Protocol.NodeOrBuilder> nodesBuilder_;
      
      public java.util.List<org.ogreg.sdis.kademlia.Protocol.Node> getNodesList() {
        if (nodesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(nodes_);
        } else {
          return nodesBuilder_.getMessageList();
        }
      }
      public int getNodesCount() {
        if (nodesBuilder_ == null) {
          return nodes_.size();
        } else {
          return nodesBuilder_.getCount();
        }
      }
      public org.ogreg.sdis.kademlia.Protocol.Node getNodes(int index) {
        if (nodesBuilder_ == null) {
          return nodes_.get(index);
        } else {
          return nodesBuilder_.getMessage(index);
        }
      }
      public Builder setNodes(
          int index, org.ogreg.sdis.kademlia.Protocol.Node value) {
        if (nodesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureNodesIsMutable();
          nodes_.set(index, value);
          onChanged();
        } else {
          nodesBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setNodes(
          int index, org.ogreg.sdis.kademlia.Protocol.Node.Builder builderForValue) {
        if (nodesBuilder_ == null) {
          ensureNodesIsMutable();
          nodes_.set(index, builderForValue.build());
          onChanged();
        } else {
          nodesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addNodes(org.ogreg.sdis.kademlia.Protocol.Node value) {
        if (nodesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureNodesIsMutable();
          nodes_.add(value);
          onChanged();
        } else {
          nodesBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addNodes(
          int index, org.ogreg.sdis.kademlia.Protocol.Node value) {
        if (nodesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureNodesIsMutable();
          nodes_.add(index, value);
          onChanged();
        } else {
          nodesBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addNodes(
          org.ogreg.sdis.kademlia.Protocol.Node.Builder builderForValue) {
        if (nodesBuilder_ == null) {
          ensureNodesIsMutable();
          nodes_.add(builderForValue.build());
          onChanged();
        } else {
          nodesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addNodes(
          int index, org.ogreg.sdis.kademlia.Protocol.Node.Builder builderForValue) {
        if (nodesBuilder_ == null) {
          ensureNodesIsMutable();
          nodes_.add(index, builderForValue.build());
          onChanged();
        } else {
          nodesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllNodes(
          java.lang.Iterable<? extends org.ogreg.sdis.kademlia.Protocol.Node> values) {
        if (nodesBuilder_ == null) {
          ensureNodesIsMutable();
          super.addAll(values, nodes_);
          onChanged();
        } else {
          nodesBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearNodes() {
        if (nodesBuilder_ == null) {
          nodes_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000020);
          onChanged();
        } else {
          nodesBuilder_.clear();
        }
        return this;
      }
      public Builder removeNodes(int index) {
        if (nodesBuilder_ == null) {
          ensureNodesIsMutable();
          nodes_.remove(index);
          onChanged();
        } else {
          nodesBuilder_.remove(index);
        }
        return this;
      }
      public org.ogreg.sdis.kademlia.Protocol.Node.Builder getNodesBuilder(
          int index) {
        return getNodesFieldBuilder().getBuilder(index);
      }
      public org.ogreg.sdis.kademlia.Protocol.NodeOrBuilder getNodesOrBuilder(
          int index) {
        if (nodesBuilder_ == null) {
          return nodes_.get(index);  } else {
          return nodesBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends org.ogreg.sdis.kademlia.Protocol.NodeOrBuilder> 
           getNodesOrBuilderList() {
        if (nodesBuilder_ != null) {
          return nodesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(nodes_);
        }
      }
      public org.ogreg.sdis.kademlia.Protocol.Node.Builder addNodesBuilder() {
        return getNodesFieldBuilder().addBuilder(
            org.ogreg.sdis.kademlia.Protocol.Node.getDefaultInstance());
      }
      public org.ogreg.sdis.kademlia.Protocol.Node.Builder addNodesBuilder(
          int index) {
        return getNodesFieldBuilder().addBuilder(
            index, org.ogreg.sdis.kademlia.Protocol.Node.getDefaultInstance());
      }
      public java.util.List<org.ogreg.sdis.kademlia.Protocol.Node.Builder> 
           getNodesBuilderList() {
        return getNodesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          org.ogreg.sdis.kademlia.Protocol.Node, org.ogreg.sdis.kademlia.Protocol.Node.Builder, org.ogreg.sdis.kademlia.Protocol.NodeOrBuilder> 
          getNodesFieldBuilder() {
        if (nodesBuilder_ == null) {
          nodesBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              org.ogreg.sdis.kademlia.Protocol.Node, org.ogreg.sdis.kademlia.Protocol.Node.Builder, org.ogreg.sdis.kademlia.Protocol.NodeOrBuilder>(
                  nodes_,
                  ((bitField0_ & 0x00000020) == 0x00000020),
                  getParentForChildren(),
                  isClean());
          nodes_ = null;
        }
        return nodesBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:org.ogreg.sdis.kademlia.Message)
    }
    
    static {
      defaultInstance = new Message(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:org.ogreg.sdis.kademlia.Message)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_org_ogreg_sdis_kademlia_Node_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_ogreg_sdis_kademlia_Node_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_org_ogreg_sdis_kademlia_Message_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_ogreg_sdis_kademlia_Message_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n src/main/protobuf/kademlia.proto\022\027org." +
      "ogreg.sdis.kademlia\"5\n\004Node\022\016\n\006nodeId\030\001 " +
      "\002(\014\022\017\n\007address\030\002 \002(\014\022\014\n\004port\030\003 \002(\r\"\245\001\n\007M" +
      "essage\022\016\n\006nodeId\030\001 \002(\014\022\r\n\005rpcId\030\002 \002(\014\0222\n" +
      "\004type\030\003 \002(\0162$.org.ogreg.sdis.kademlia.Me" +
      "ssageType\022\013\n\003key\030\004 \001(\014\022\014\n\004data\030\005 \001(\014\022,\n\005" +
      "nodes\030\006 \003(\0132\035.org.ogreg.sdis.kademlia.No" +
      "de*t\n\013MessageType\022\014\n\010REQ_PING\020\000\022\r\n\tREQ_S" +
      "TORE\020\001\022\021\n\rREQ_FIND_NODE\020\002\022\022\n\016REQ_FIND_VA" +
      "LUE\020\003\022\017\n\013RSP_SUCCESS\020\n\022\020\n\014RSP_IO_ERROR\020\013",
      "B\nB\010Protocol"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_org_ogreg_sdis_kademlia_Node_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_org_ogreg_sdis_kademlia_Node_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_org_ogreg_sdis_kademlia_Node_descriptor,
              new java.lang.String[] { "NodeId", "Address", "Port", },
              org.ogreg.sdis.kademlia.Protocol.Node.class,
              org.ogreg.sdis.kademlia.Protocol.Node.Builder.class);
          internal_static_org_ogreg_sdis_kademlia_Message_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_org_ogreg_sdis_kademlia_Message_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_org_ogreg_sdis_kademlia_Message_descriptor,
              new java.lang.String[] { "NodeId", "RpcId", "Type", "Key", "Data", "Nodes", },
              org.ogreg.sdis.kademlia.Protocol.Message.class,
              org.ogreg.sdis.kademlia.Protocol.Message.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
